<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>



    <!-- 
    JavaScript-də try...catch ifadəsi, müəyyən bir kod blokunda səhv və xətaları idarə etmək üçün istifadə olunur. try bloku daxilindəki kod icra olunur və əgər bir səhv baş verərsə, bu səhv catch bloku tərəfindən tutulur və işlənir. 


    try {
    // Səhv yarada biləcək kod
        var x = y + 10; // "y" təyin edilmədiyi üçün bir ReferenceError yaranacaq
} catch (səhv) {
    // Səhv tutulduğunda ediləcək işlər
        console.log("Bir səhv baş verdi:", səhv.message); // Səhvin mesajını konsola yazdır

        Bu kodda, try bloku daxilindəki kod icra olunmağa cəhd edilir. Əgər bu kodda bir səhv baş verərsə, bu səhv catch bloku tərəfindən tutulur. Tutulan səhvin məlumatları səhv adlı bir dəyişəndə saxlanılır və bu məlumatlar istənilən əməllər üçün istifadə edilə bilər. Məsələn, səhvin mesajı konsola yazdırıla bilər.
}

-->
</body>

</html>